### ISSUE TITLE
Error Trying to Connect

### ISSUE THREAD

**Issue by MartinPJones** [laf/russound#10]
Hi there,
When attempting to connect, I get the following error:
```OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied```

My code is pretty basic, just 
```from russound import russound
import time

IP_ADDRESS = '192.168.1.60'
PORT = 9621

def main():
    x = russound.Russound(IP_ADDRESS, PORT)
    x.connect()
    x.is_connected()
    for zone in range (1,5):
        x.set_power('1', zone, '1')
```

So basically verbatim the examples. Traceback:
```Traceback (most recent call last):
  File "file.py", line 16, in <module>
    main()
  File "file.py", line 12, in main
    x.set_power('1', zone, '1')
  File "C:\Users\user\PycharmProjects\russound\venv\lib\site-packages\russound\russound.py", line 82, in set_power
    self.send_data(send_msg)
  File "C:\Users\user\PycharmProjects\russound\venv\lib\site-packages\russound\russound.py", line 245, in send_data
    self.sock.send(data)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no add
ress was supplied
```

Thanks!

**Comment by MartinPJones** [comment]
Turns out if you send it to the wrong host, it's gonna have issues connecting.
